<template>
    <div>
        <h1>Admin</h1>
        <h1>Admin</h1>
        <h1>Admin</h1>
        <h1>Admin</h1>
        <h1>Admin</h1>
        <h1>Admin</h1>
        <h1>Admin</h1>
    </div>
</template>